### ISSUE TITLE
ISO 8601 date-time without time zone designator not interpreted correctly (works on iOS)

### ISSUE THREAD

**Issue by mlenkeit** [eu-digital-green-certificates/dgc-certlogic-android#53] opened 2021-08-11 06:44 UTC
## Describe the bug

A date/date-time value like `2021-02-04T00:00:00` without a time zone designator, when used in a DCC and checked by a corresponding rule, leads to `open` on Android instead of pass or fail. This is the case for many DCCs from Bulgaria. 

## Expected behaviour

The date-time format is correctly parsed because it is a valid ISO 8601 date-time representation, see https://en.wikipedia.org/wiki/ISO_8601#Times

## Steps to reproduce the issue

Create a vaccination certificate with `dt` set to `2021-02-04T00:00:00` and check against the German rule set.

## Technical details

n/a

## Possible Fix

n/a

## Additional context

- works on iOS

**Comment by oleksandrsarapulovgl** [comment] 2021-08-19 07:50
Hi @mlenkeit ! I created a vaccination certificate with `dt` set to `2021-02-04T00:00:00`: `{
  "v": [
    {
      "dn": 1,
      "ma": "ORG-100001699",
      "vp": "J07BX03",
      "dt": "2021-02-04T00:00:00",
      "co": "AT",
      "ci": "URN:UVCI:V1:DE:3DDOQI3EYQEFN61MBQIWH8YKP4",
      "mp": "EU/1/20/1507",
      "is": "asfadf",
      "sd": 2,
      "tg": "840539006"
    }
  ],
  "nam": {
    "fnt": "STANDARDISEDFAMILY"
  },
  "ver": "1.3.0",
  "dob": ""
}`


And tested it over German rules. It works fine for me: 
![Screenshot_1629359250](https://user-images.githubusercontent.com/82441124/130029404-e9d54c14-dd9f-45c0-8b1a-2e31606b62d7.png).

Could you please clarify if I'm missing something?

**Comment by mtwalli** [comment] 2021-08-21 08:41
@oleksandrsarapulovgl , Can you please also set `dob` for ex. `"1980-03-21T00:00:00"` ?

I think the issue is happening here:
https://github.com/eu-digital-green-certificates/dgc-certlogic-android/blob/main/engine/src/main/java/dgca/verifier/app/engine/DefaultCertLogicEngine.kt#L105-L112

it throws an exception:
```console 
E/CertLogicEngineWrapper: Errors during validation of VR-DE-0004
    java.time.format.DateTimeParseException: not an allowed date or date-time format
        at eu.ehn.dcc.certlogic.CertlogicKt.evaluate(certlogic.kt:863)
        at eu.ehn.dcc.certlogic.CertlogicKt.evaluateInfix(certlogic.kt:149)
        at eu.ehn.dcc.certlogic.CertlogicKt.evaluate(certlogic.kt:623)
        at eu.ehn.dcc.certlogic.CertlogicKt.evaluate(certlogic.kt:129)
        at dgca.verifier.app.engine.DefaultJsonLogicValidator.isDataValid(DefaultJsonLogicValidator.kt:1)
        at dgca.verifier.app.engine.DefaultCertLogicEngine.checkRule(DefaultCertLogicEngine.kt:21)
        at dgca.verifier.app.engine.DefaultCertLogicEngine.validate(DefaultCertLogicEngine.kt:83)

```
 I think:
 - the state is misleading. should not the state be `Result.FAIL` not `Result.OPEN` ?
 - Allow such `dob` format  if some EU countries (BG) issue certificates with such `dob`

**Comment by vaubaehn** [comment] 2021-08-23 19:43
@mlenkeit 
> A date/date-time value like `2021-02-04T00:00:00` without a time zone designator, when used in a DCC and checked by a corresponding rule, leads to `open` on Android instead of pass or fail.

> works on iOS

What is the result on iOS? Fail or Pass?

@mtwalli @mlenkeit 
> I think the state is misleading. should not the state be `Result.FAIL` not `Result.OPEN` ?

`Result.FAIL` in this case in general is probably not a good solution, as the exact time taking the correct time zone into account _could_ be specified/evaluated - either technically (rule runner engine or wallet app would need to be extended accordingly) or manually. If it's done technically, there would be a clear result 'pass' or 'fail'. If must be done manually (when it can't be implemented technically), then rule runner engine should result in open to signal a manual check is needed.

What [wikipedia](https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators) also writes:
>Time zones in ISO 8601 are represented as local time (with the location unspecified), as UTC, or as an offset from UTC.
Local time (unqualified)
>If no UTC relation information is given with a time representation, the time is assumed to be in local time. While it may be safe to assume local time when communicating in the same time zone, it is ambiguous when used in communicating across different time zones. Even within a single geographic time zone, some local times will be ambiguous if the region observes daylight saving time. It is usually preferable to indicate a time zone (zone designator) using the standard's notation. 

So, it's an unpleasant situation with the Bulgarian certificates affected, because
* they are valid in general
* there may be many out there in the wild
* the time zone could be specified in general (Bulgarian local time)
* but it needs additional effort, either
* technically: implementing a check in either rule runner enigne where the DCC was issued and use the corresponding time zone to check the rule, or in the wallet app by appending the correct timezone before data are submitted to the rule runner,
* manually (open status): checking what would be the local time zone and decide if DCC is still in range of validity.

A long term solution seems to be necessary, as this issue is also very critical with Test DCCs (because NAAT and RAT have a very limited validity).

For now it doesn't look like that the DCC schema 1.3.0 explicitly requires a time zone set for field `dt`:
https://github.com/ehn-dcc-development/ehn-dcc-schema/blob/a603410d760fefc9073931c8c807759d9714c136/DCC.combined-schema.json#L191-L195

The same seems to be true for fields `sc `(sample collected) for tests
https://github.com/ehn-dcc-development/ehn-dcc-schema/blob/a603410d760fefc9073931c8c807759d9714c136/DCC.combined-schema.json#L239-L243

and for the validity range of the recovery certificate:
https://github.com/ehn-dcc-development/ehn-dcc-schema/blob/a603410d760fefc9073931c8c807759d9714c136/DCC.combined-schema.json#L296-L305

Has there already been a kind of agreement within the national subgroups on how to handle 'unqualified' timestamps without time zone? Probably it's a good idea to clarify the specs accordingly. And it would need a decision whether all unqualified timestamps already issued result in 'open status' in the future, or CertlogicEngine/wallet apps need to be enhanced. I guess, all available options may cause some headache...

**Comment by vaubaehn** [comment] 2021-08-23 22:21
Ok, I found this:
https://github.com/ehn-dcc-development/dgc-business-rules/blob/main/certlogic/specification/README.md#dates-and-date-times

Timestamps without time zone designator should be parsed as UTC (Z), and the result should be 'pass' or 'fail' accordingly.
So, then this issue here is actually a bug within CertlogicEngine implementation for Android.

@mlenkeit do the results on iOS differ like expected in 'pass' and 'fail', depending on exceeding time of validity?

**Comment by rgrenz** [comment] 2021-08-24 10:19
Hi @vaubaehn, I will try to answer since @mlenkeit is on vacation. However, I only started working on DCCs very recently so I am very certainly not yet qualified as a full stand-in.

The DCC schemes you referred to show that vaccination and recovery certificates indeed do not require a time zone (since they only need to be ISO8601 complete dates). From a practical perspective this should be fine since rules regarding e.g. vaccination certificates only specify day-specific offsets (like 'valid after 14 days') and exact time is not of importance.

Regarding test certificates, the `sc` field for tests is required to be of format date-time, which according to [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) is only complete with time offset information. So as long as the scheme is implemented correctly in Bulgaria, we should not encounter `sc` fields without time zone information. The German Corona-Warn-App rejects test certificates with `sc` fields that violate this constraint.

In our case @mtwalli found that our issue can most probably be fixed by updating our dependency to lib version 0.9. As we can see in your screenshot, the 365-day rule results in `PASS` even without time zone information.

**Comment by vaubaehn** [comment] 2021-08-24 17:48
Hi @rgrenz , thanks for your response! I hope mlenkeit has an enjoyable time off.

> The DCC schemes you referred to show that vaccination and recovery certificates indeed do not require a time zone (since they only need to be ISO8601 complete dates). From a practical perspective this should be fine since rules regarding e.g. vaccination certificates only specify day-specific offsets (like 'valid after 14 days') and exact time is not of importance.

Yes, right. I had some discussions from the past in my mind at what point in time CWA should display a state of 'full vaccination', and I thought that date-time was taken into account... But no, I looked it up in the code, it's indeed about full days (starting at 00:00:00 local time zone) - so, it's perfectly in line with business rule validation.

> In our case @mtwalli found that our issue can most probably be fixed by updating our dependency to lib version 0.9. As we can see in your screenshot, the 365-day rule results in `PASS` even without time zone information.

If this is the case, then everything should be fine for this issue here.

> Regarding test certificates, the `sc` field for tests is required to be of format date-time, which according to [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) is only complete with time offset information. So as long as the scheme is implemented correctly in Bulgaria, we should not encounter `sc` fields without time zone information. The German Corona-Warn-App rejects test certificates with `sc` fields that violate this constraint.

In this case we should not expect any problem here (except users complaining not being able to add DCCs with flawed timestamps).

> I only started working on DCCs very recently

I'm very sad about some devs left the Android team recently, but I'm happy that 'we' still have @mtwalli , and that you also joined. Welcome in our small universe 😉

**Comment by mtwalli** [comment] 2021-08-25 10:35
@rgrenz  Thanks for the nice summary 👍🏼 ,
I will just reference the commit, that I think it fixed already the issue in latest version https://github.com/ehn-dcc-development/dgc-business-rules/commit/1d8dcebc88717fb5c8a943391e0190924be84af1

**Comment by Hendrik-Schmidt-Schierhorn-TSI** [comment] 2021-09-01 13:49
Currently we are not able to reproduce an issue here. Issue will be closed so far.

**Closed by Hendrik-Schmidt-Schierhorn-TSI** 2021-09-01 13:49 UTC
Labels: bug
